service: lfr-discordWebhook

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  stage: ${opt:stage, self:provider.stage}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
      Resource:
        - "Fn::ImportValue": ${self:custom.stage}-AlertsTableArn

functions:
  discordWebhook:
    handler: discordWebhook.main
    name: ${self:custom.stage}-lfr-discordWebhook
    description: "Discord Webhook that sends data to subscribed channels."
    memorySize: 128
    timeout: 15
    events:
      - stream:
          type: dynamodb
          batchSize: 100
          startingPosition: LATEST
          arn:
            Fn::ImportValue: ${self:custom.stage}-CharactersTableStreamArn
    environment:
      tableName: ${file(../alertsDatabase/serverless.yml):custom.tableName}
