service: lfr-discord-webhook

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  stage: ${opt:stage, self:provider.stage}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

  environment:
    tableName: ${file(../alertsDatabase/serverless.yml):custom.tableName}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
      Resource:
        - "Fn::ImportValue": ${self:custom.stage}-AlertsTableArn

functions:
  discordWebhook:
    handler: discordWebhook.main
    name: ${self:custom.stage}-lfr-discord-webhook
    description: "Discord Webhook that sends data to subscribed channels."
    memorySize: 128
    timeout: 10
    events:
      - stream:
          type: dynamodb
          batchSize: 100
          startingPosition: LATEST
          arn:
            Fn::ImportValue: ${self:custom.stage}-CharactersTableStreamArn
    environment:
      characterDataEndpoint: https://raider.io/api/v1/characters/profile?region=us
      webhookEndpoint: https://discordapp.com/api/webhooks
