service: lfr-createAlert

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  stage: ${opt:stage, self:provider.stage}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
      Resource:
        - "Fn::ImportValue": ${self:custom.stage}-AlertsTableArn

functions:
  createAlert:
    handler: createAlert.main
    name: ${self:custom.stage}-lfr-createAlert
    description: "Function to get Discord access token and store in Database with alert settings"
    memorySize: 128
    timeout: 15
    events:
      - http:
          path: alerts
          method: post
          cors: True
    environment:
      tableName: ${file(../alertsDatabase/serverless.yml):custom.tableName}
      clientId: "TMP"
      clientSecret: "TMP"
