service: lfr-deleteAlert

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  stage: ${opt:stage, self:provider.stage}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
      Resource:
        - "Fn::ImportValue": ${self:custom.stage}-AlertsTableArn

functions:
  deleteAlert:
    handler: deleteAlert.main
    name: ${self:custom.stage}-lfr-deleteAlert
    description: "Function to delete alert from both Discord and database"
    memorySize: 128
    timeout: 15
    events:
      - http:
          path: alerts
          method: delete
          cors: True
    environment:
      tableName: ${file(../alertsDatabase/serverless.yml):custom.tableName}
      clientId: "TMP"
      clientSecret: "TMP"
