service: lfr-webScraper

frameworkVersion: "1.43.0"

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  stage: ${opt:stage, self:provider.stage}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
      Resource:
        - "Fn::ImportValue": ${self:custom.stage}-CharactersTableArn

functions:
  webScraper:
    handler: webScraper.main
    name: ${self:custom.stage}-lfr-webScraper
    description: "Web scraper to get character data."
    memorySize: 128
    timeout: 15
    events:
      - schedule: rate(5 minutes)
    environment:
      tableName: ${file(../charactersDatabase/serverless.yml):custom.tableName}
