service: lfr-characters-database

custom:
  stage: ${opt:stage, self:provider.stage}
  tableName: ${self:custom.stage}-lfr-characters
  tableThroughputs:
    prod: 5
    default: 1
  tableThroughput: ${self:custom.tableThroughputs.${self:custom.stage}, self:custom.tableThroughputs.default}

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

resources:
  Resources:
    CharactersTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: Name
            AttributeType: S
          - AttributeName: Realm
            AttributeType: S
        KeySchema:
          - AttributeName: Name
            KeyType: HASH
          - AttributeName: Realm
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: ${self:custom.tableThroughput}
          WriteCapacityUnits: ${self:custom.tableThroughput}
        TimeToLiveSpecification:
          AttributeName: TTL
          Enabled: true
        StreamSpecification:
          StreamViewType: NEW_IMAGE

  Outputs:
    CharactersTableArn:
      Value:
        Fn::GetAtt:
          - CharactersTable
          - Arn
      Export:
        Name: ${self:custom.stage}-CharactersTableArn
    CharactersTableStreamArn:
      Value:
        Fn::GetAtt:
          - CharactersTable
          - StreamArn
      Export:
        Name: ${self:custom.stage}-CharactersTableStreamArn
